#!/usr/bin/sh
COMMAND="$1"
KERNEL_VERSION="$2"

command -v luft-trust >/dev/null || exit 0

case "$COMMAND" in
    add)
        if [ -n "$KERNEL_INSTALL_STAGING_AREA" ] && [ -f "$KERNEL_INSTALL_STAGING_AREA/initrd" ]; then
            exec luft-trust startup add "$KERNEL_VERSION" --initrd "$KERNEL_INSTALL_STAGING_AREA/initrd"
        fi
        exec luft-trust startup add "$KERNEL_VERSION"
        ;;
    remove)
        exec luft-trust startup remove "$KERNEL_VERSION"
        ;;
esac
