use crate::{
    protocols::{OutputManagementState, ToplevelIconGlobal},
    state::KestrelState,
    vicinae_hotkey::VicinaeHotkeyState,
};
#[cfg(feature = "session-backend")]
use smithay::wayland::{dmabuf::DmabufGlobal, drm_syncobj::DrmSyncobjState};
use smithay::{
    reexports::wayland_server::DisplayHandle,
    utils::{Clock, Monotonic},
    wayland::{
        alpha_modifier::AlphaModifierState,
        background_effect::BackgroundEffectState,
        commit_timing::CommitTimingManagerState,
        cursor_shape::CursorShapeManagerState,
        dmabuf::DmabufState,
        fifo::FifoManagerState,
        foreign_toplevel_list::ForeignToplevelListState,
        fractional_scale::FractionalScaleManagerState,
        idle_inhibit::IdleInhibitManagerState,
        image_capture_source::{ImageCaptureSourceState, OutputCaptureSourceState},
        image_copy_capture::ImageCopyCaptureState,
        input_method::InputMethodManagerState,
        keyboard_shortcuts_inhibit::KeyboardShortcutsInhibitState,
        output::OutputManagerState,
        pointer_constraints::PointerConstraintsState,
        pointer_gestures::PointerGesturesState,
        presentation::PresentationState,
        relative_pointer::RelativePointerManagerState,
        session_lock::SessionLockManagerState,
        shell::xdg::decoration::XdgDecorationState,
        single_pixel_buffer::SinglePixelBufferState,
        text_input::TextInputManagerState,
        viewporter::ViewporterState,
        xdg_activation::XdgActivationState,
        xdg_foreign::XdgForeignState,
    },
};

pub struct ProtocolState {
    pub xdg_activation: XdgActivationState,
    pub xdg_foreign: XdgForeignState,
    pub foreign_toplevel_list: ForeignToplevelListState,
    pub keyboard_shortcuts_inhibit: KeyboardShortcutsInhibitState,
    pub dmabuf: DmabufState,
    #[cfg(feature = "session-backend")]
    pub dmabuf_global: Option<DmabufGlobal>,
    #[cfg(feature = "session-backend")]
    pub drm_syncobj: Option<DrmSyncobjState>,
    _xdg_decoration: XdgDecorationState,
    _cursor_shape: CursorShapeManagerState,
    _fractional_scale: FractionalScaleManagerState,
    _viewporter: ViewporterState,
    _toplevel_icon: ToplevelIconGlobal,
    _text_input: TextInputManagerState,
    _input_method: InputMethodManagerState,
    _presentation: PresentationState,
    _output: OutputManagerState,
    _single_pixel_buffer: SinglePixelBufferState,
    _background_effect: BackgroundEffectState,
    pub vicinae_hotkey: VicinaeHotkeyState,
    _alpha_modifier: AlphaModifierState,
    _relative_pointer: RelativePointerManagerState,
    _pointer_constraints: PointerConstraintsState,
    _pointer_gestures: PointerGesturesState,
    _fifo: FifoManagerState,
    _commit_timing: CommitTimingManagerState,
    pub session_lock: SessionLockManagerState,
    _image_capture_source: ImageCaptureSourceState,
    pub output_capture_source: OutputCaptureSourceState,
    pub image_copy_capture: ImageCopyCaptureState,
    _idle_inhibit: IdleInhibitManagerState,
    pub output_management: OutputManagementState,
}

impl ProtocolState {
    pub fn new(display: &DisplayHandle) -> Self {
        Self {
            xdg_activation: XdgActivationState::new::<KestrelState>(display),
            xdg_foreign: XdgForeignState::new::<KestrelState>(display),
            foreign_toplevel_list: ForeignToplevelListState::new::<KestrelState>(display),
            keyboard_shortcuts_inhibit: KeyboardShortcutsInhibitState::new::<KestrelState>(display),
            dmabuf: DmabufState::new(),
            #[cfg(feature = "session-backend")]
            dmabuf_global: None,
            #[cfg(feature = "session-backend")]
            drm_syncobj: None,
            _xdg_decoration: XdgDecorationState::new::<KestrelState>(display),
            _cursor_shape: CursorShapeManagerState::new::<KestrelState>(display),
            _fractional_scale: FractionalScaleManagerState::new::<KestrelState>(display),
            _viewporter: ViewporterState::new::<KestrelState>(display),
            _toplevel_icon: ToplevelIconGlobal::new(display),
            _text_input: TextInputManagerState::new::<KestrelState>(display),
            _input_method: InputMethodManagerState::new::<KestrelState, _>(display, |_| true),
            _presentation: PresentationState::new::<KestrelState>(
                display,
                Clock::<Monotonic>::new().id() as u32,
            ),
            _output: OutputManagerState::new_with_xdg_output::<KestrelState>(display),
            _single_pixel_buffer: SinglePixelBufferState::new::<KestrelState>(display),
            _background_effect: BackgroundEffectState::new::<KestrelState>(display),
            vicinae_hotkey: VicinaeHotkeyState::new(display),
            _alpha_modifier: AlphaModifierState::new::<KestrelState>(display),
            _relative_pointer: RelativePointerManagerState::new::<KestrelState>(display),
            _pointer_constraints: PointerConstraintsState::new::<KestrelState>(display),
            _pointer_gestures: PointerGesturesState::new::<KestrelState>(display),
            _fifo: FifoManagerState::new::<KestrelState>(display),
            _commit_timing: CommitTimingManagerState::new::<KestrelState>(display),
            session_lock: SessionLockManagerState::new::<KestrelState, _>(display, |_| true),
            _image_capture_source: ImageCaptureSourceState::new(),
            output_capture_source: OutputCaptureSourceState::new::<KestrelState>(display),
            image_copy_capture: ImageCopyCaptureState::new::<KestrelState>(display),
            _idle_inhibit: IdleInhibitManagerState::new::<KestrelState>(display),
            output_management: OutputManagementState::new(display),
        }
    }
}
