[app]
id = "com.lantharos.magpie"
name = "Magpie"
generic_name = "Media Viewer"
categories = ["AudioVideo", "Audio", "Video", "Player", "Graphics", "Viewer"]
keywords = ["photos", "pictures", "images", "image viewer", "gallery", "video player", "videos", "movies", "music player", "music", "audio", "songs", "pdf", "document viewer", "preview", "viewer", "fonts", "font viewer", "typeface", "media player", "loupe", "totem", "showtime", "evince", "papers", "vlc", "gnome-font-viewer"]
version = "0.1.0"
icon = "public/favicon.svg"
cargo_manifest = "desktop/Cargo.toml"
mime_types = [
	"image/jpeg",
	"image/png",
	"image/apng",
	"image/gif",
	"image/webp",
	"image/avif",
	"image/svg+xml",
	"image/svg+xml-compressed",
	"image/heic",
	"image/heif",
	"image/jxl",
	"image/bmp",
	"image/tiff",
	"image/vnd.microsoft.icon",
	"image/x-tga",
	"image/qoi",
	"image/x-exr",
	"image/jp2",
	"image/x-portable-anymap",
	"image/x-portable-pixmap",
	"video/mp4",
	"video/webm",
	"video/x-matroska",
	"video/quicktime",
	"video/ogg",
	"video/x-m4v",
	"video/3gpp",
	"video/x-msvideo",
	"audio/mpeg",
	"audio/flac",
	"audio/ogg",
	"audio/x-vorbis+ogg",
	"audio/opus",
	"audio/x-opus+ogg",
	"audio/wav",
	"audio/x-wav",
	"audio/aac",
	"audio/mp4",
	"audio/x-m4a",
	"audio/webm",
	"audio/x-matroska",
	"application/pdf",
	"font/ttf",
	"font/otf",
	"font/collection",
	"font/woff",
	"font/woff2",
	"application/x-font-ttf",
	"application/x-font-otf",
	"application/font-woff"
]

[app.extensions]
"audio/webm" = ["weba"]

[install]
command = "cargo run --manifest-path desktop/Cargo.toml --"

[web]
root = "."
dist = "dist"
entry = "dist/index.html"
build = "bun run build"
local_files = true
