[package]
name = "magpie"
version = "0.1.0"
description = "Photos, videos, music and documents for Luft"
authors = ["Kristof"]
license = "MIT"
edition = "2024"
rust-version = "1.93"

[lib]
name = "magpie_lib"

[dependencies]
dirs = "7.0.0"
gio = "0.22.10"
gio-unix = "0.22.8"
glycin = { version = "4.0.0", default-features = false, features = ["tokio"] }
imagesize = "0.15.0"
kamadak-exif = "0.6.1"
lofty = "0.25.4"
luft-app = { path = "../../../packages/app", features = ["apps", "thumbnails"] }
matroska-demuxer = "0.8.1"
parking_lot = "0.12.5"
sabine = { git = "https://github.com/Lantharos/Sabine", tag = "v0.32" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", default-features = false, features = ["rt-multi-thread"] }
zbus = { version = "5.19.0", default-features = false, features = ["blocking-api", "tokio"] }
