[package]
name = "rover"
version = "0.1.0"
description = "A modern file manager for Linux"
authors = ["Kristof"]
license = "MIT"
edition = "2024"
rust-version = "1.90"

[lib]
name = "rover_lib"

[dependencies]
sabine = { git = "https://github.com/Lantharos/Sabine", tag = "v0.30" }
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt", "process", "macros"] }
walkdir = "2.5.0"
trash = "5.2.9"
dirs = "7.0.0"
mime_guess = "2.0.5"
chrono = "0.4.45"
parking_lot = "0.12.5"
open = "5.4.4"
libc = "0.2"
zbus = { version = "5.19.0", default-features = false, features = ["tokio"] }
url = "2.5.8"
percent-encoding = "2.3.2"
