option('camera_monitor',
  type: 'boolean',
  value: true,
  description: 'Enable the camera monitor'
)

option('networkmanager',
  type: 'boolean',
  value: true,
  description: 'Enable NetworkManager support'
)

option('systemd',
  type: 'boolean',
  value: true,
  description: 'Enable systemd integration'
)
