export type Named = readonly [text: string, name: string, keywords?: string];

export const CHARACTERS: readonly (readonly [title: string, characters: readonly Named[]])[] = [
  ['Arrows', [
    ['←', 'leftwards arrow'], ['↑', 'upwards arrow'], ['→', 'rightwards arrow'], ['↓', 'downwards arrow'],
    ['↔', 'left right arrow'], ['↕', 'up down arrow'], ['↖', 'north west arrow'], ['↗', 'north east arrow'],
    ['↘', 'south east arrow'], ['↙', 'south west arrow'], ['⇐', 'leftwards double arrow'], ['⇑', 'upwards double arrow'],
    ['⇒', 'rightwards double arrow', 'implies'], ['⇓', 'downwards double arrow'], ['⇔', 'left right double arrow', 'if and only if'],
    ['⟶', 'long rightwards arrow'], ['⟵', 'long leftwards arrow'], ['↩', 'leftwards arrow with hook', 'return'],
    ['↪', 'rightwards arrow with hook'], ['↺', 'anticlockwise open circle arrow', 'undo'], ['↻', 'clockwise open circle arrow', 'redo refresh'],
    ['⇄', 'rightwards arrow over leftwards arrow', 'swap'], ['⇥', 'rightwards arrow to bar', 'tab'], ['⏎', 'return symbol', 'enter'],
  ]],
  ['Math', [
    ['±', 'plus minus'], ['×', 'multiplication sign', 'times'], ['÷', 'division sign', 'divide'], ['−', 'minus sign'],
    ['≠', 'not equal to'], ['≈', 'almost equal to', 'approximately'], ['≡', 'identical to'], ['≤', 'less than or equal to'],
    ['≥', 'greater than or equal to'], ['∞', 'infinity'], ['√', 'square root'], ['∑', 'summation', 'sum sigma'],
    ['∏', 'product'], ['∫', 'integral'], ['∂', 'partial differential'], ['∆', 'increment', 'delta'],
    ['∇', 'nabla'], ['∈', 'element of'], ['∉', 'not an element of'], ['∩', 'intersection'],
    ['∪', 'union'], ['⊂', 'subset of'], ['⊃', 'superset of'], ['∀', 'for all'],
    ['∃', 'there exists'], ['∅', 'empty set'], ['¬', 'not sign'], ['∧', 'logical and'],
    ['∨', 'logical or'], ['∝', 'proportional to'], ['∠', 'angle'], ['⊥', 'perpendicular'],
    ['°', 'degree'], ['′', 'prime', 'minutes feet'], ['″', 'double prime', 'seconds inches'], ['‰', 'per mille'],
    ['½', 'one half', 'fraction'], ['⅓', 'one third', 'fraction'], ['⅔', 'two thirds', 'fraction'], ['¼', 'one quarter', 'fraction'],
    ['¾', 'three quarters', 'fraction'], ['¹', 'superscript one'], ['²', 'superscript two', 'squared'], ['³', 'superscript three', 'cubed'],
    ['π', 'pi', 'greek'], ['µ', 'micro', 'mu greek'], ['Ω', 'omega', 'ohm greek'], ['α', 'alpha', 'greek'],
    ['β', 'beta', 'greek'], ['γ', 'gamma', 'greek'], ['δ', 'delta', 'greek'], ['θ', 'theta', 'greek'],
    ['λ', 'lambda', 'greek'], ['σ', 'sigma', 'greek'], ['φ', 'phi', 'greek'], ['ω', 'small omega', 'greek'],
  ]],
  ['Currency', [
    ['€', 'euro'], ['£', 'pound'], ['¥', 'yen', 'yuan'], ['¢', 'cent'], ['$', 'dollar'], ['₹', 'indian rupee'],
    ['₽', 'ruble'], ['₩', 'won'], ['₪', 'new shekel'], ['₫', 'dong'], ['₺', 'turkish lira'], ['₴', 'hryvnia'],
    ['₦', 'naira'], ['₱', 'peso'], ['₿', 'bitcoin'], ['₣', 'franc'], ['₵', 'cedi'], ['₸', 'tenge'],
    ['₼', 'manat'], ['₾', 'lari'], ['¤', 'currency sign'],
  ]],
  ['Punctuation', [
    ['…', 'ellipsis'], ['–', 'en dash'], ['—', 'em dash'], ['•', 'bullet'], ['·', 'middle dot'], ['«', 'left guillemet', 'quote'],
    ['»', 'right guillemet', 'quote'], ['‹', 'single left guillemet', 'quote'], ['›', 'single right guillemet', 'quote'], ['„', 'low double quotation mark'],
    ['“', 'left double quotation mark'], ['”', 'right double quotation mark'], ['‘', 'left single quotation mark'],
    ['’', 'right single quotation mark', 'apostrophe'], ['¡', 'inverted exclamation mark'], ['¿', 'inverted question mark'],
    ['§', 'section'], ['¶', 'pilcrow', 'paragraph'], ['†', 'dagger'], ['‡', 'double dagger'], ['※', 'reference mark'], ['‽', 'interrobang'],
  ]],
  ['Signs and shapes', [
    ['©', 'copyright'], ['®', 'registered'], ['™', 'trade mark'], ['№', 'numero sign', 'number'], ['℃', 'degree celsius'],
    ['℉', 'degree fahrenheit'], ['✓', 'check mark', 'tick'], ['✗', 'ballot x', 'cross'], ['★', 'black star'], ['☆', 'white star'],
    ['●', 'black circle'], ['○', 'white circle'], ['■', 'black square'], ['□', 'white square'], ['◆', 'black diamond'],
    ['◇', 'white diamond'], ['▲', 'black up triangle'], ['△', 'white up triangle'], ['▼', 'black down triangle'],
    ['▽', 'white down triangle'], ['♠\u{FE0E}', 'spade suit'], ['♣\u{FE0E}', 'club suit'], ['♥\u{FE0E}', 'heart suit'], ['♦\u{FE0E}', 'diamond suit'],
    ['♪', 'eighth note', 'music'], ['♫', 'beamed eighth notes', 'music'], ['⌘', 'command key'], ['⌥', 'option key'],
    ['⌃', 'control key'], ['⇧', 'shift key'], ['⌫', 'erase to the left', 'backspace'], ['⎋', 'escape key'],
  ]],
];

export const KAOMOJI: readonly Named[] = [
  ['¯\\_(ツ)_/¯', 'shrug', 'whatever dunno'],
  ['(╯°□°)╯︵ ┻━┻', 'table flip', 'angry rage'],
  ['┬─┬ノ( º _ ºノ)', 'putting the table back', 'calm'],
  ['( ͡° ͜ʖ ͡°)', 'lenny face', 'smirk'],
  ['ಠ_ಠ', 'look of disapproval', 'stare'],
  ['(づ｡◕‿‿◕｡)づ', 'hug', 'love'],
  ['(ノ◕ヮ◕)ノ*:･ﾟ✧', 'sparkles', 'excited magic'],
  ['\\(^o^)/', 'hooray', 'cheer happy'],
  ['٩(◕‿◕｡)۶', 'cheering', 'happy'],
  ['(^▽^)', 'grinning', 'happy'],
  ['(≧◡≦)', 'delighted', 'happy'],
  ['(*^‿^*)', 'blushing', 'shy happy'],
  ['(✿◠‿◠)', 'flower smile', 'happy cute'],
  ['(｡♥‿♥｡)', 'in love', 'heart'],
  ['(˘³˘)♥', 'kiss', 'love'],
  ['(｡•̀ᴗ-)✧', 'wink', 'cheeky'],
  ['(⌐■_■)', 'cool', 'sunglasses'],
  ['( •_•)>⌐■-■', 'deal with it', 'sunglasses cool'],
  ['(ง\'̀-\'́)ง', 'ready to fight', 'fists'],
  ['(°ロ°)', 'shocked', 'surprised'],
  ['ヽ(°〇°)ﾉ', 'astonished', 'surprised'],
  ['(⊙_⊙)', 'wide eyed', 'stare surprised'],
  ['(o_O)', 'confused', 'what'],
  ['(¬_¬)', 'suspicious', 'side eye'],
  ['(；一_一)', 'unimpressed', 'annoyed'],
  ['(>_<)', 'frustrated', 'ugh'],
  ['(╥﹏╥)', 'crying', 'sad tears'],
  ['(T_T)', 'sobbing', 'sad tears'],
  ['(╬ Ò﹏Ó)', 'furious', 'angry'],
  ['(-_-) zzZ', 'sleepy', 'tired sleep'],
  ['(´• ω •`)', 'shy', 'bashful'],
  ['(っ˘ω˘ς )', 'cosy', 'comfy content'],
  ['♪(´▽｀)', 'singing', 'music happy'],
  ['(ﾟ▽ﾟ)/', 'waving', 'hello hi'],
  ['ʕ•ᴥ•ʔ', 'bear', 'animal cute'],
  ['(=^･ω･^=)', 'cat', 'animal cute'],
  ['U・ᴥ・U', 'dog', 'animal puppy'],
  ['( ˘▽˘)っ♨', 'hot drink', 'tea coffee'],
  ['(＠_＠)', 'dizzy', 'confused'],
  ['¯\\(°_o)/¯', 'confused shrug', 'dunno'],
];
