[app]
id = "com.lantharos.tern"
name = "Tern"
generic_name = "Terminal"
categories = ["System", "TerminalEmulator"]
keywords = ["terminal", "console", "shell", "command line", "command prompt", "cmd", "powershell", "prompt", "cli", "tty", "bash", "zsh", "fish", "xterm", "konsole", "ptyxis"]
version = "0.1.0"
icon = "public/favicon.svg"
cargo_manifest = "desktop/Cargo.toml"

[install]
command = "cargo run --manifest-path desktop/Cargo.toml --"

[web]
root = "."
dist = "dist"
entry = "dist/index.html"
build = "bun run build"
