[app]
id = "com.lantharos.settings"
name = "Settings"
generic_name = "Settings"
categories = ["Settings", "System"]
keywords = ["preferences", "control panel", "control center", "system settings", "system preferences", "configuration", "options", "setup"]
version = "0.1.0"
icon = "static/favicon.svg"
cargo_manifest = "desktop/Cargo.toml"
mime_types = ["x-scheme-handler/kestrel-settings"]

[install]
command = "cargo run --manifest-path desktop/Cargo.toml --"

[web]
root = "."
dist = "build"
entry = "build/index.html"
build = "bun run build"
local_files = true
