foreach file : [
  'OpenRunde-Regular.otf', 'OpenRunde-Medium.otf', 'OpenRunde-Semibold.otf', 'OpenRunde-Bold.otf', 'OFL.txt',
  'MapleMono-NF-Regular.ttf', 'MapleMono-NF-Italic.ttf', 'MapleMono-NF-Bold.ttf', 'MapleMono-NF-BoldItalic.ttf', 'MapleMono-OFL.txt',
]
  fs.copyfile(file, install: true, install_dir: pkgdatadir / 'fonts')
endforeach
