[package]
name = "sushi"
description = "Display, rendering and boot integration shared by the Sushi daemon and tools"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
drm.workspace = true
drm-ffi = "0.9.1"
libc.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
sushi-scene.workspace = true
tiny-skia = { workspace = true, features = ["std", "simd"] }

[lints]
workspace = true
