[package]
name = "sushid"
description = "The Sushi boot splash daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
rustix.workspace = true
sushi.workspace = true

[lints]
workspace = true
