export type Named = readonly [text: string, name: string, keywords?: string];

export const KAOMOJI: readonly Named[] = [
  ['¯\\_(ツ)_/¯', 'shrug', 'whatever dunno'],
  ['(╯°□°)╯︵ ┻━┻', 'table flip', 'angry rage'],
  ['┬─┬ノ( º _ ºノ)', 'putting the table back', 'calm'],
  ['( ͡° ͜ʖ ͡°)', 'lenny face', 'smirk'],
  ['ಠ_ಠ', 'look of disapproval', 'stare'],
  ['(づ｡◕‿‿◕｡)づ', 'hug', 'love'],
  ['(ノ◕ヮ◕)ノ*:･ﾟ✧', 'sparkles', 'excited magic'],
  ['\\(^o^)/', 'hooray', 'cheer happy'],
  ['٩(◕‿◕｡)۶', 'cheering', 'happy'],
  ['(^▽^)', 'grinning', 'happy'],
  ['(≧◡≦)', 'delighted', 'happy'],
  ['(*^‿^*)', 'blushing', 'shy happy'],
  ['(✿◠‿◠)', 'flower smile', 'happy cute'],
  ['(｡♥‿♥｡)', 'in love', 'heart'],
  ['(˘³˘)♥', 'kiss', 'love'],
  ['(｡•̀ᴗ-)✧', 'wink', 'cheeky'],
  ['(⌐■_■)', 'cool', 'sunglasses'],
  ['( •_•)>⌐■-■', 'deal with it', 'sunglasses cool'],
  ['(ง\'̀-\'́)ง', 'ready to fight', 'fists'],
  ['(°ロ°)', 'shocked', 'surprised'],
  ['ヽ(°〇°)ﾉ', 'astonished', 'surprised'],
  ['(⊙_⊙)', 'wide eyed', 'stare surprised'],
  ['(o_O)', 'confused', 'what'],
  ['(¬_¬)', 'suspicious', 'side eye'],
  ['(；一_一)', 'unimpressed', 'annoyed'],
  ['(>_<)', 'frustrated', 'ugh'],
  ['(╥﹏╥)', 'crying', 'sad tears'],
  ['(T_T)', 'sobbing', 'sad tears'],
  ['(╬ Ò﹏Ó)', 'furious', 'angry'],
  ['(-_-) zzZ', 'sleepy', 'tired sleep'],
  ['(´• ω •`)', 'shy', 'bashful'],
  ['(っ˘ω˘ς )', 'cosy', 'comfy content'],
  ['♪(´▽｀)', 'singing', 'music happy'],
  ['(ﾟ▽ﾟ)/', 'waving', 'hello hi'],
  ['ʕ•ᴥ•ʔ', 'bear', 'animal cute'],
  ['(=^･ω･^=)', 'cat', 'animal cute'],
  ['U・ᴥ・U', 'dog', 'animal puppy'],
  ['( ˘▽˘)っ♨', 'hot drink', 'tea coffee'],
  ['(＠_＠)', 'dizzy', 'confused'],
  ['¯\\(°_o)/¯', 'confused shrug', 'dunno'],
];
